config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
    get 'preview', on: :member
    get 'search', on: :collection
    post 'search', to: 'articles#find', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  # validates :body, presence: true, length: { minimum: 10 }

  # before_validation :check_before_validation, if: :title?

  # after_save :after_save_method
  # after_commit :after_commit_method

  private

  def check_title_presence
    p 'in check_title_presence'
    :title?
  end

  def after_save_method
    p "after_save_method"
  end

  def after_commit_method
    p "after_commit_method"
  end

  def check_before_validation
    title.upcase!
    if body.length < 10
      self.body = body.ljust(10,'.')
    end
    p 'In check_before_validation'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  scope :findbyuser, ->(id = 1) { where(user_id: id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def preview
    @article = Article.find(params[:id])
  end

  def find
    @articles = Article.all
    article = @articles.find_by(title: params[:title])
    if article
      redirect_to article_path(article)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<h2>Joins</h2>
<table border='1'>
  <tr>
    <td>Id</td>
    <td>title</td>
    <td>body</td>
    <td>created_at</td>
    <td>updated_at</td>
  </tr>
  <% @articles.joins(:comments).to_a.each do |record| %>
    <tr>
      <td><%= record.id %></td>
      <td><%= record.title %></td>
      <td><%= record.body %></td>
      <td><%= record.created_at %></td>
      <td><%= record.updated_at %></td>
    </tr>
  <% end %>
</table>

<h2>Preload</h2>
<table border='1'>
  <tr>
    <td>Id</td>
    <td>title</td>
    <td>body</td>
    <td>created_at</td>
    <td>updated_at</td>
  </tr>
  <% @articles.preload(:comments).to_a.each do |record| %>
    <tr>
      <td><%= record.id %></td>
      <td><%= record.title %></td>
      <td><%= record.body %></td>
      <td><%= record.created_at %></td>
      <td><%= record.updated_at %></td>
    </tr>
  <% end %>
</table>

<h2>Eager load</h2>
<table border='1'>
  <tr>
    <td>Id</td>
    <td>title</td>
    <td>body</td>
    <td>created_at</td>
    <td>updated_at</td>
  </tr>
  <% @articles.eager_load(:comments).to_a.each do |record| %>
    <tr>
      <td><%= record.id %></td>
      <td><%= record.title %></td>
      <td><%= record.body %></td>
      <td><%= record.created_at %></td>
      <td><%= record.updated_at %></td>
    </tr>
  <% end %>
</table>

<ul>
  <% @articles.each do |article| %>
    <li>
      <b><%= link_to "#{article.title} ▻", article %></b>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/preview.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>

<% if(@article.comments.length > 0) %>
  <h2>Comments</h2>
  <%= render @article.comments %>
<% end %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/articles/search.html.erb
<h1>Search Article</h1>

<%= form_with model: @article do |f| %>
  <%= f.label :title, "Enter Title:" %>
  <%= f.text_field :title %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>

<% if(@article.comments.length > 0) %>
  <h2>Comments</h2>
  <%= render @article.comments.findbyuser %>
<% end %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div class='comment'>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :user_id %><br>
    <%= form.number_field :user_id %>
  </p>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>